spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: SecretPasswordForRedis
  freemarker:
    cache: false
    suffix: .ftl
  jwt:
    secret: VkYp3s5v8y/B?E(H+MbQeThWmZq4t7w9
x-private-key: ea4bf8a1-d400-4447-8d1f-803d366da71c